apiVersion: v1
kind: ServiceAccount
metadata:
  name: clawdbot-billy
  namespace: clawdbots-dev
  labels:
    platform: clawdbots
    agent: "billy"
  annotations:
    iam.gke.io/gcp-service-account: clawdbot-billy@brandlovers-prod.iam.gserviceaccount.com
