apiVersion: v1
kind: ServiceAccount
metadata:
  name: clawdbot-neuron
  namespace: clawdbots-dev
  labels:
    platform: clawdbots
    agent: "neuron"
  annotations:
    iam.gke.io/gcp-service-account: clawdbot-neuron@brandlovers-prod.iam.gserviceaccount.com
